import { useState } from "react";
import { useLanguage } from "../../context/LanguageContext";

export default function ImageGenerator() {
  const { dict, lang } = useLanguage();
  const [prompt, setPrompt] = useState("");
  const [result, setResult] = useState(null);

  const generate = () => {
    if (!prompt.trim()) return;

    // Fake image (real API can be added later)
    setResult("https://via.placeholder.com/512x512?text=AI+Image");
  };

  return (
    <div className="container py-4" style={{ direction: lang === "fa" ? "rtl" : "ltr" }}>
      <h3 className="fw-bold mb-3">{dict.image_gen}</h3>

      <textarea
        className="form-control mb-3"
        placeholder={dict.image_prompt_placeholder}
        rows={4}
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
      />

      <button className="btn btn-primary w-100 mb-4" onClick={generate}>
        {dict.generate}
      </button>

      {result && (
        <div className="text-center">
          <img
            src={result}
            alt="Generated by AI"
            className="img-fluid rounded-4 shadow"
            style={{ maxWidth: 400 }}
          />
        </div>
      )}
    </div>
  );
}
